export const marketListings = [
  {
    id: "SKN-04821",
    name: "Ava Rose Sterling",
    age: 28,
    occupation: "Editorial photographer",
    description:
      "A calm visual storyteller with a sharp eye for people, places, and the small details others miss.",
    owner: "@nightarchive",
    price: "4,800 USDC",
    media: [
      {
        type: "image",
        src: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&crop=faces&w=900&h=1200&q=85",
      },
      {
        type: "video",
        src: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
        poster:
          "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&crop=entropy&w=900&h=1200&q=85",
      },
    ],
  },
  {
    id: "SKN-09317",
    name: "Thea Bennett",
    age: 34,
    occupation: "Industrial designer",
    description:
      "Practical, exacting, and quietly inventive. Turns rough ideas into objects people want to keep.",
    owner: "@formandfunction",
    price: "6,250 USDC",
    media: [
      {
        type: "image",
        src: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&crop=faces&w=900&h=1200&q=85",
      },
      {
        type: "image",
        src: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&crop=entropy&w=900&h=1200&q=85",
      },
      {
        type: "image",
        src: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&crop=top&w=900&h=1200&q=85",
      },
    ],
  },
  {
    id: "SKN-11204",
    name: "Mina Okafor",
    age: 31,
    occupation: "Cultural strategist",
    description:
      "Connects emerging ideas with communities and brands, bringing clarity to complex cultural shifts.",
    owner: "@commonthread",
    price: "5,100 USDC",
    media: [
      {
        type: "image",
        src: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&crop=faces&w=900&h=1200&q=85",
      },
    ],
  },
  {
    id: "SKN-15690",
    name: "Lucia Meyer",
    age: 39,
    occupation: "Documentary filmmaker",
    description:
      "Patient observer and experienced field producer, known for honest stories with a human pulse.",
    owner: "@longtake",
    price: "7,400 USDC",
    media: [
      {
        type: "image",
        src: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&crop=faces&w=900&h=1200&q=85",
      },
      {
        type: "image",
        src: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&crop=entropy&w=900&h=1200&q=85",
      },
    ],
  },
  {
    id: "SKN-20341",
    name: "Nora Elise Laurent",
    age: 26,
    occupation: "Ceramic artist",
    description:
      "Creates tactile tableware and sculptural pieces shaped by natural textures and slow, deliberate craft.",
    owner: "@softkiln",
    price: "3,950 USDC",
    media: [
      {
        type: "image",
        src: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&crop=faces&w=900&h=1200&q=85",
      },
    ],
  },
  {
    id: "SKN-22785",
    name: "Eliana Voss",
    age: 37,
    occupation: "Urban planner",
    description:
      "Designs walkable neighborhoods and public spaces where practical systems leave room for everyday life.",
    owner: "@streetlogic",
    price: "6,800 USDC",
    media: [
      {
        type: "image",
        src: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&crop=faces&w=900&h=1200&q=85",
      },
    ],
  },
  {
    id: "SKN-24109",
    name: "Sienna Mae Brooks",
    age: 29,
    occupation: "Sound designer",
    description:
      "Builds layered soundscapes for film and games, balancing precise detail with an instinct for atmosphere.",
    owner: "@fieldrecording",
    price: "5,600 USDC",
    media: [
      {
        type: "image",
        src: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&crop=faces&w=900&h=1200&q=85",
      },
    ],
  },
  {
    id: "SKN-26844",
    name: "Adriana Cole Rivera",
    age: 42,
    occupation: "Marine biologist",
    description:
      "Studies coastal ecosystems and translates field research into clear stories for communities and policymakers.",
    owner: "@bluecurrent",
    price: "8,150 USDC",
    media: [
      {
        type: "image",
        src: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&crop=faces&w=900&h=1200&q=85",
      },
    ],
  },
  {
    id: "SKN-30418",
    name: "Leila Haddad",
    age: 33,
    occupation: "Product researcher",
    description:
      "Finds the unmet needs behind user behavior and turns messy evidence into focused product direction.",
    owner: "@signalroom",
    price: "5,850 USDC",
    media: [
      {
        type: "image",
        src: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&crop=faces&w=900&h=1200&q=85",
      },
    ],
  },
  {
    id: "SKN-33762",
    name: "Noa Min Park",
    age: 30,
    occupation: "Robotics engineer",
    description:
      "Develops reliable machines for unpredictable environments with equal attention to hardware and human operators.",
    owner: "@movingparts",
    price: "7,900 USDC",
    media: [
      {
        type: "image",
        src: "https://images.unsplash.com/photo-1524250502761-1ac6f2e30d43?auto=format&fit=crop&crop=faces&w=900&h=1200&q=85",
      },
    ],
  },
  {
    id: "SKN-36511",
    name: "Camille Dubois",
    age: 36,
    occupation: "Art conservator",
    description:
      "Protects fragile artworks through patient investigation, precise restoration, and respect for every trace of history.",
    owner: "@quietmuseum",
    price: "6,450 USDC",
    media: [
      {
        type: "image",
        src: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&crop=faces&w=900&h=1200&q=85",
      },
    ],
  },
  {
    id: "SKN-40173",
    name: "Sofia Alvarez",
    age: 27,
    occupation: "Culinary director",
    description:
      "Shapes seasonal menus around local ingredients, generous hospitality, and flavors that reward curiosity.",
    owner: "@supperclub",
    price: "4,700 USDC",
    media: [
      {
        type: "image",
        src: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&crop=faces&w=900&h=1200&q=85",
      },
    ],
  },
  {
    id: "SKN-43826",
    name: "Priya Nair",
    age: 40,
    occupation: "Climate policy analyst",
    description:
      "Turns climate data and regulation into practical strategies for cities, institutions, and long-term investors.",
    owner: "@futureweather",
    price: "8,600 USDC",
    media: [
      {
        type: "image",
        src: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&crop=faces&w=900&h=1200&q=85",
      },
    ],
  },
  {
    id: "SKN-47295",
    name: "Felicia Hartmann",
    age: 32,
    occupation: "Type designer",
    description:
      "Draws expressive type systems that stay readable across identities, interfaces, and many languages.",
    owner: "@baselinegrid",
    price: "5,300 USDC",
    media: [
      {
        type: "image",
        src: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&crop=faces&w=900&h=1200&q=85",
      },
    ],
  },
  {
    id: "SKN-50124",
    name: "Maya Chen",
    age: 35,
    occupation: "Architect",
    description: "Designs adaptable homes shaped by daylight, durable materials, and the changing rhythms of their residents.",
    owner: "@northlight",
    price: "7,150 USDC",
    media: [{ type: "image", src: "https://randomuser.me/api/portraits/women/21.jpg" }],
  },
  {
    id: "SKN-51482",
    name: "Elena Petrova",
    age: 28,
    occupation: "Choreographer",
    description: "Builds expressive movement from close observation, disciplined rehearsal, and an instinct for musical space.",
    owner: "@afterimage",
    price: "4,900 USDC",
    media: [{ type: "image", src: "https://randomuser.me/api/portraits/women/22.jpg" }],
  },
  {
    id: "SKN-52739",
    name: "Amara Diallo",
    age: 38,
    occupation: "Data journalist",
    description: "Finds human stories inside complex datasets and makes public-interest reporting clear without flattening nuance.",
    owner: "@openrecords",
    price: "6,750 USDC",
    media: [{ type: "image", src: "https://randomuser.me/api/portraits/women/23.jpg" }],
  },
  {
    id: "SKN-54106",
    name: "Iris van Dijk",
    age: 41,
    occupation: "Landscape architect",
    description: "Creates resilient public landscapes where water, plants, wildlife, and city life can share limited ground.",
    owner: "@commonfield",
    price: "8,300 USDC",
    media: [{ type: "image", src: "https://randomuser.me/api/portraits/women/24.jpg" }],
  },
  {
    id: "SKN-55671",
    name: "Hana Sato",
    age: 32,
    occupation: "Game producer",
    description: "Keeps ambitious creative teams aligned, protecting both the player experience and the people building it.",
    owner: "@checkpoint",
    price: "6,200 USDC",
    media: [{ type: "image", src: "https://randomuser.me/api/portraits/women/25.jpg" }],
  },
  {
    id: "SKN-56934",
    name: "Zoe Williams",
    age: 29,
    occupation: "Aerospace engineer",
    description: "Develops lightweight flight systems with methodical testing, precise communication, and calm under pressure.",
    owner: "@highorbit",
    price: "8,850 USDC",
    media: [{ type: "image", src: "https://randomuser.me/api/portraits/women/26.jpg" }],
  },
  {
    id: "SKN-58320",
    name: "Fatima Rahman",
    age: 44,
    occupation: "Public health researcher",
    description: "Studies how local conditions shape health outcomes and turns evidence into programs communities can use.",
    owner: "@caremap",
    price: "7,600 USDC",
    media: [{ type: "image", src: "https://randomuser.me/api/portraits/women/27.jpg" }],
  },
  {
    id: "SKN-59748",
    name: "Clara Moretti",
    age: 31,
    occupation: "Furniture maker",
    description: "Makes restrained, durable furniture through careful joinery and a deep respect for each piece of timber.",
    owner: "@goodgrain",
    price: "5,450 USDC",
    media: [{ type: "image", src: "https://randomuser.me/api/portraits/women/28.jpg" }],
  },
  {
    id: "SKN-61205",
    name: "Valentina Costa",
    age: 36,
    occupation: "Fashion archivist",
    description: "Preserves garments, documents their provenance, and reconnects design history with contemporary practice.",
    owner: "@garmentmemory",
    price: "6,100 USDC",
    media: [{ type: "image", src: "https://randomuser.me/api/portraits/women/29.jpg" }],
  },
  {
    id: "SKN-62577",
    name: "Aisha Thompson",
    age: 39,
    occupation: "Civil rights attorney",
    description: "Combines rigorous casework with patient advocacy, helping institutions become more accountable and accessible.",
    owner: "@equalground",
    price: "8,050 USDC",
    media: [{ type: "image", src: "https://randomuser.me/api/portraits/women/30.jpg" }],
  },
  {
    id: "SKN-63918",
    name: "Yuna Kim",
    age: 27,
    occupation: "Interaction designer",
    description: "Designs digital tools that feel direct and humane, especially when the systems behind them are complicated.",
    owner: "@clearstate",
    price: "5,750 USDC",
    media: [{ type: "image", src: "https://randomuser.me/api/portraits/women/31.jpg" }],
  },
  {
    id: "SKN-65342",
    name: "Grace Osei",
    age: 43,
    occupation: "Renewable energy consultant",
    description: "Guides practical energy transitions by balancing engineering realities, policy constraints, and local priorities.",
    owner: "@gridshift",
    price: "9,100 USDC",
    media: [{ type: "image", src: "https://randomuser.me/api/portraits/women/32.jpg" }],
  },
  {
    id: "SKN-66809",
    name: "Ines Ferreira",
    age: 34,
    occupation: "Investigative editor",
    description: "Helps reporting teams test assumptions, follow difficult evidence, and publish stories built to withstand scrutiny.",
    owner: "@secondsource",
    price: "6,950 USDC",
    media: [{ type: "image", src: "https://randomuser.me/api/portraits/women/33.jpg" }],
  },
  {
    id: "SKN-68153",
    name: "Daria Kovacs",
    age: 30,
    occupation: "Computational linguist",
    description: "Builds language technology that handles ambiguity, regional variation, and the ways people actually communicate.",
    owner: "@syntaxerror",
    price: "7,350 USDC",
    media: [{ type: "image", src: "https://randomuser.me/api/portraits/women/34.jpg" }],
  },
  {
    id: "SKN-69524",
    name: "Layla Morgan",
    age: 26,
    occupation: "Wildlife photographer",
    description: "Works quietly in remote habitats, creating patient images that reveal behavior without disturbing it.",
    owner: "@hiddentrail",
    price: "5,200 USDC",
    media: [{ type: "image", src: "https://randomuser.me/api/portraits/women/35.jpg" }],
  },
  {
    id: "SKN-70986",
    name: "Renata Silva",
    age: 37,
    occupation: "Social entrepreneur",
    description: "Builds sustainable services around overlooked local needs, measuring success through lasting community ownership.",
    owner: "@sharedvalue",
    price: "7,050 USDC",
    media: [{ type: "image", src: "https://randomuser.me/api/portraits/women/36.jpg" }],
  },
  {
    id: "SKN-72431",
    name: "Alina Popescu",
    age: 42,
    occupation: "Neuroscientist",
    description: "Investigates memory and attention through careful experiments, open methods, and unusually clear explanation.",
    owner: "@graymatter",
    price: "8,700 USDC",
    media: [{ type: "image", src: "https://randomuser.me/api/portraits/women/37.jpg" }],
  },
  {
    id: "SKN-73865",
    name: "Maeve Collins",
    age: 33,
    occupation: "Book curator",
    description: "Builds thoughtful collections that connect overlooked writers, independent presses, and curious new readers.",
    owner: "@marginnotes",
    price: "4,650 USDC",
    media: [{ type: "image", src: "https://randomuser.me/api/portraits/women/38.jpg" }],
  },
  {
    id: "SKN-75214",
    name: "Samira Benali",
    age: 40,
    occupation: "Transport economist",
    description: "Evaluates how mobility investments affect time, access, and opportunity across different neighborhoods.",
    owner: "@movingcity",
    price: "7,800 USDC",
    media: [{ type: "image", src: "https://randomuser.me/api/portraits/women/39.jpg" }],
  },
  {
    id: "SKN-76680",
    name: "Evelyn Rhodes",
    age: 45,
    occupation: "Perfumer",
    description: "Composes distinctive fragrances from precise materials, long memory, and an exceptional sense of balance.",
    owner: "@volatile_notes",
    price: "9,400 USDC",
    media: [{ type: "image", src: "https://randomuser.me/api/portraits/women/40.jpg" }],
  },
] as const
